# Generated by Django 4.0.5 on 2022-06-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgupload/files/covers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
