# Generated by Django 4.0.5 on 2022-06-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgupload', '0002_imagetable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('image_table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imgupload.imagetable')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
